### ISSUE TITLE
Error on launching blank clone

### ISSUE THREAD

**Issue by sunwaterdev** [BeaconMCDev/BeaconMC#1]
**Describe the bug**
Error on launching blank clone
**To Reproduce**
Clone & run
**Expected behavior**
Run the server
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux/Ubuntu 24.04 LTS
**Additional context**
Traceback (most recent call last):
  File "/home/jules/Documents/BeaconMC/main.py", line 1345, in <module>
    log('Starting Plugin APi', 3)
  File "/home/jules/Documents/BeaconMC/main.py", line 160, in log
    with open(logfile, "+a") as file:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'logs/log1.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jules/Documents/BeaconMC/main.py", line 1351, in <module>
    log("FATAL ERROR : An error occured while running the server : uncaught exception.", 100)
  File "/home/jules/Documents/BeaconMC/main.py", line 160, in log
    with open(logfile, "+a") as file:

**Comment by FewerElk** [comment]
Is it solved with your commit https://github.com/FewerTeam/BeaconMC/compare/761fc6f07d30...279452d2ce2d ?

**Comment by sunwaterdev** [comment]
Yep sorry
